"""empty message

Revision ID: 16dacdd8ff8a
Revises: bff139ae3fe1
Create Date: 2017-05-06 18:42:25.454888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dacdd8ff8a'
down_revision = 'bff139ae3fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('lastedit', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_lastedit'), 'articles', ['lastedit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_lastedit'), table_name='articles')
    op.drop_column('articles', 'lastedit')
    # ### end Alembic commands ###
