"""empty message

Revision ID: 9b3053593f69
Revises: 16dacdd8ff8a
Create Date: 2017-05-20 23:08:26.583434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3053593f69'
down_revision = '16dacdd8ff8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'body_html')
    # ### end Alembic commands ###
